// map
export const CHANGE_MAP_LAYOUT = 'CHANGE_MAP_LAYOUT';
// search condition
export const VISIBLE_SEARCH_CONDITION = 'VISIBLE_SEARCH_CONDITION';
export const LOAD_SEARCH_CONDITION = 'LOAD_SEARCH_CONDITION';
export const UPDATE_SEARCH_CONDITION = 'UPDATE_SEARCH_CONDITION';
export const DETERMINE_SEARCH_CONDITION = 'DETERMINE_SEARCH_CONDITION';
export const RESTORE_SEARCH_CONDITION = 'RESTORE_SEARCH_CONDITION';
export const CLEAR_SEARCH_CONDITION = 'CLEAR_SEARCH_CONDITION';
export const UPDATE_LINES = 'UPDATE_LINES';
export const VISIBLE_MORDAL_CIRCLE_SEARCH = 'VISIBLE_CIRCLE_SEARCH';
export const UPDATE_PREFECTURES = 'UPDATE_PREFECTURES';
// circle search
export const CIRCLE_SEARCH = 'CIRCLE_SEARCH';
export const SET_CENTER_COORDINATE = 'SET_CENTER_COORDINATE';
export const UPDATE_RADIUS = 'UPDATE_RADIUS';
// rectangle search
export const VISIBLE_RECTANGLE_SEARCH = 'VISIBLE_RECTANGLE_SEARCH';
export const UPDATE_BOUNDS = 'UPDATE_BOUNDS';
// search
export const BEFORE_EXECUTE_SEARCH = 'BEFORE_EXECUTE_SEARCH';
export const EXECUTE_SEARCH = 'EXECUTE_SEARCH';
// settings
export const END_BALLOON_SETTING_ACQUISITION = 'END_BALLOON_SETTING_ACQUISITION';
export const END_BALLOON_SETTING_UPDATE = 'END_BALLOON_SETTING_UPDATE';
