// map
export const CHANGE_MAP_LAYOUT = 'CHANGE_MAP_LAYOUT';
// search conditions
export const VISIBLE_SEARCH_CONDITIONS = 'VISIBLE_SEARCH_CONDITIONS';
export const VISIBLE_MORDAL_CIRCLE_SEARCH = 'VISIBLE_CIRCLE_SEARCH';
export const UPDATE_SEARCH_CONDITIONS = 'UPDATE_SEARCH_CONDITION';
// circle search
export const CIRCLE_SEARCH = 'CIRCLE_SEARCH';
export const SET_CENTER_COORDINATE = 'SET_CENTER_COORDINATE';
export const UPDATE_RADIUS = 'UPDATE_RADIUS';
// rectangle search
export const VISIBLE_RECTANGLE_SEARCH = 'VISIBLE_RECTANGLE_SEARCH';
export const UPDATE_BOUNDS = 'UPDATE_BOUNDS';
// search
export const BEFORE_EXECUTE_SEARCH = 'BEFORE_EXECUTE_SEARCH';
export const EXECUTE_SEARCH = 'EXECUTE_SEARCH';
// settings
export const END_BALLOON_SETTING_ACQUISITION = 'END_BALLOON_SETTING_ACQUISITION';
export const END_BALLOON_SETTING_UPDATE = 'END_BALLOON_SETTING_UPDATE';
