import IDateRange from '../date-range';
import IFreeWord from '../free-word';
import INumberRange from '../number-range';
import ITransportation from '../transportation';
import IArea from './area';

export default interface ISearchCondition {
  readonly stageStatus: number[];
  readonly salesAt?: IDateRange;
  // readonly boardConstructionAt: IDateRange;
  // readonly constructionAt: IDateRange;
  // readonly completionAt: IDateRange;
  readonly transportations?: ITransportation[];
  readonly areas?: IArea[];
  readonly name?: IFreeWord;
  // readonly company: IFreeWord;
  // readonly developer: IFreeWord;
  // readonly constractor: IFreeWord;
  // readonly designer: IFreeWord;
  // readonly seller: IFreeWord;
  // readonly manager: IFreeWord;
  readonly unitCount?: INumberRange;
  // readonly topFloor: INumberRange;
  // readonly parkingCount: INumberRange;
  // readonly parkingInstallationRate: INumberRange;
  // readonly groundArea: INumberRange;
  // readonly buildingArea: INumberRange;
  // readonly floorArea: INumberRange;
  // readonly saleCount: INumberRange;
  // readonly applyCount: INumberRange;
  // readonly firstMonthApplyRate: INumberRange;
  // readonly priceTotal: INumberRange;
  // readonly areaTotal: INumberRange;
  // readonly priceMin: INumberRange;
  // readonly areaMin: INumberRange;
  // readonly tsuboMin: INumberRange;
  // readonly priceAverage: INumberRange;
  // readonly areaAverage: INumberRange;
  // readonly tsuboAverage: INumberRange;
  // readonly priceMax: INumberRange;
  // readonly areaMax: INumberRange;
  // readonly tsuboMax: INumberRange;
  [key: string]: any;
}
