import IDateRange from '../date-range';
import IFreeWord from '../free-word';
import INumberRange from '../number-range';
import ITransportation from '../transportation';
import IArea from './area';

export default interface ISearchCondition {
  readonly stageStatus: number[];
  readonly salesAt?: IDateRange|null;
  // readonly boardConstructionAt: IDateRange|null;
  // readonly constructionAt: IDateRange|null;
  // readonly completionAt: IDateRange|null;
  readonly transportations?: ITransportation[]|null;
  readonly areas?: IArea[]|null;
  readonly name?: IFreeWord|null;
  // readonly company: IFreeWord|null;
  // readonly developer: IFreeWord|null;
  // readonly constractor: IFreeWord|null;
  // readonly designer: IFreeWord|null;
  // readonly seller: IFreeWord|null;
  // readonly manager: IFreeWord|null;
  readonly unitCount?: INumberRange|null;
  // readonly topFloor: INumberRange|null;
  // readonly parkingCount: INumberRange|null;
  // readonly parkingInstallationRate: INumberRange|null;
  // readonly groundArea: INumberRange|null;
  // readonly buildingArea: INumberRange|null;
  // readonly floorArea: INumberRange|null;
  // readonly saleCount: INumberRange|null;
  // readonly applyCount: INumberRange|null;
  // readonly firstMonthApplyRate: INumberRange|null;
  // readonly priceTotal: INumberRange|null;
  // readonly areaTotal: INumberRange|null;
  // readonly priceMin: INumberRange|null;
  // readonly areaMin: INumberRange|null;
  // readonly tsuboMin: INumberRange|null;
  // readonly priceAverage: INumberRange|null;
  // readonly areaAverage: INumberRange|null;
  // readonly tsuboAverage: INumberRange|null;
  // readonly priceMax: INumberRange|null;
  // readonly areaMax: INumberRange|null;
  // readonly tsuboMax: INumberRange|null;
  [key: string]: any;
}
